[workspace]
members = [
    "emulator",
    "data_builder",
    "inky",
    "inky_graphics",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1"
futures = "0.3"
hostname = "0.4"
image = "0.25"
inky = { path = "inky" }
inky_graphics = { path = "inky_graphics" }
jiff = { version = "0.2", features = ["serde"] }
nmrs = "2"
quick-xml = "0.39"
rand = "0.9"
reqwest = "0.13"
rkyv = { version = "0.8", features = ["unaligned"] }
rkyv_util = "0.1.0-alpha.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
softbuffer = "0.4"
spidev = "0.7"
tokio = { version = "1", features = ["full"] }
tokio-gpiod = "0.3"
winit = "0.30"

[package]
name = "eink_frame"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
futures.workspace = true
hostname.workspace = true
image.workspace = true
inky.workspace = true
inky_graphics.workspace = true
jiff.workspace = true
nmrs.workspace = true
reqwest.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[profile.deploy]
inherits = "release"
opt-level = "s"
strip = true
panic = "abort"
codegen-units = 1

[patch.crates-io]
tokio-gpiod = { path = "../gpiod-rs/tokio" }
rend = { path = "../rend" }
