[package]
name = "inky"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
tokio.workspace = true

[target.'cfg(hardware)'.dependencies]
spidev.workspace = true
tokio-gpiod.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(hardware)'] }
